version: "3"
services:
  php:
    build:
     context: .
     dockerfile: ./Dockerfile
    volumes:
      - ./sample:/var/www/html/sample
      - ./docker/app/php.ini:/usr/local/lib/php.ini
      - ./docker/app/httpd.conf:/etc/apache2/httpd.conf
    tty: true
    ports:
     - 80:80
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cake_php
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - 3306:3306
